### ISSUE TITLE
Asignacion modulo 3.1

### ISSUE THREAD

**Issue by 95102023** [SistemasTecTlaxiaco/cristian#11]
![3 1](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/919f6f37-b0b4-44df-9326-123dab54ee8d)

![3 1 1](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/1b1a18d1-8321-4e36-9a98-a51e8c629d62)

![3 1 2](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/692185eb-afd9-4cc1-a1b1-27ac2bd6affe)

![3 1 3](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/644e3797-c0b3-4c37-b3f1-d72b7c10439b)

![3 1 4](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/08551308-b42a-4f59-8228-b8b75c2617d6)

**Comment by josealfredo79** [comment]
Super...la tarea esta bien hecha...
