### ISSUE TITLE
Modulo 3.4 Asignacion 

### ISSUE THREAD

**Issue by 95102023** [SistemasTecTlaxiaco/cristian#14]
https://classroom.github.com/a/Srumiqk7

![image](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/01beddfb-3a88-406a-8031-31a3255e6cfe)

![2 4 1](https://github.com/SistemasTecTlaxiaco/cristian/assets/137822125/3b938a7e-b7c2-42fe-879f-dc6e0fa2accc)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
